### PR TITLE
Mzscheme to racket

### PR DESCRIPTION
**Pull request by glebm**
1. Converts all the Racket source code from the legazy mzscheme syntax to `#lang racket/base`.
2. Replaces `util.rkt` with standard Racket methods.
3. Renames scheme grammar target to racket.
4. Adds a basic test for generating parsers in each target language.

This PR is branched off #57, #57 should be merged first.

These changes reduce the final executable size down from 6.8 MiB to 2.8 MiB, and reduces `time build/waxeye` by half.

### CODE REVIEW

**Comment by darmie** [comment]
Hmm... This is a lot of changes. Good stuff. Would need to personally
adjust to this change going forward.

**Comment by glebm** [comment]
Luckily, most of the changes are mechanical.

**Comment by glebm** [comment]
@orlandohill Rebased

**Comment by orlandohill** [comment]
Thanks! It's great to finally move from PLT Scheme to Racket :)

**Pull request merged**
