### PR TITLE
Non-recursive engine for JavaScript

### PR DESCRIPTION
**Pull request by JoshuaGross**
I believe this is end-user-API compatible with previous implementation, but the source generation needs to be updated. More-or-less a direct translation of Match4.

### CODE REVIEW

**Comment by orlandohill** [comment]
Thanks Joshua! I'll merge this in and add the code generation.

**Comment by JoshuaGross** [comment]
Sounds good. Any ETA? I'm happy to help with code generation for the Java and C implementations (coming soon) once this one is done.

**Comment by orlandohill** [comment]
By the end of Wednesday, if not tomorrow. Sorry for the delay.

Yes, it'd be great if you could help with Java and C.

**Comment by JoshuaGross** [comment]
Appreciate it! I'm in a rush on my end but I realize my deadlines aren't your concern. Really appreciate the help.

**Comment by JoshuaGross** [comment]
Any updates on this?

**Comment by JoshuaGross** [comment]
Hey Orlando :) Any chance you'll still be able to look at this?

**Comment by orlandohill** [comment]
Hey Joshua,
Yes, sorry. Haven't had as much spare time and energy as had hoped.

I'll look through it on the weekend, and send you an update.

**Pull request merged**
