### PR TITLE
Non-recursive javascript engine and generator

### PR DESCRIPTION
**Pull request by adabru**
Hi,

in response to bug https://github.com/orlandohill/waxeye/issues/23 there was a new Javasript-engine implemented and pull requested https://github.com/orlandohill/waxeye/pull/24 by Joshua Gross

The pull request only missed the generator. I changed `javascript.scm` to enable the new parser. There is one breaking change:
- Non-terminals are always lowercased currently, in the pull request they are not.

I do not get any 'too much recursion'-errors anymore, though the time-performance has dropped. As mentioned in the Readme, to test the new parser: `node test/javascript/test.js`, there is no output if all tests pass.

### CODE REVIEW

**Comment by adabru** [comment]
In the end I wrote my own parser generator in livescript with some feature extensions, but basically same syntaxed grammar files. It integrates multipass parsing and shall implement incremental parsing.

**Comment by orlandohill** [comment]
Sounds great, Adam! Sorry that I've been so unresponsive.

**Comment by glebm** [comment]
Hi @orlandohill! Is there anything preventing this from getting merged?

**Comment by orlandohill** [comment]
Hi Gleb,

No, when I think about it now, it should be fine.

I had wanted to write the code myself, or at least give it a thorough review before merging it. After a string of bad luck with head injuries, that's not going to happen anytime soon.

However, enough clearly smart people have written and reviewed the code, so I guess it's not irresponsible if I don't review it myself.

A contribution policy based on other contributors doing the code review. Does that sound sensible?

**Comment by glebm** [comment]
@orlandohill Sorry to hear about your head injuries.

> A contribution policy based on other contributors doing the code review. Does that sound sensible?

I've seen this approach work well for other projects. Sounds good.

> However, enough clearly smart people have written and reviewed the code, so I guess it's not irresponsible if I don't review it myself.

@JoshuaGross, @adabru, perhaps you are interested in doing reviews or being granted commit rights?

I have not yet reviewed or tested this code as we're just started getting started with waxeye so 
I can't yet vouch for this PR.

**Comment by orlandohill** [comment]
> I've seen this approach work well for other projects. Sounds good.

Great, I'll go with that.

**Pull request merged**
