### PR TITLE
Support compiling to all architectures necessary for iOS support.

### PR DESCRIPTION
**Pull request by JoshuaGross**
Hey Orlando, love the project. Let me know if you're interested in this change and want me to clean it up / restructure it / reformat it in any way.

### CODE REVIEW

**Comment by orlandohill** [comment]
Hey Joshua,
Thanks for taking the time to do this. It looks great!
Would it be possible to rearrange things so that the 'lib' target stays the same, and a target of another name is used to cross-compile for iOS?

**Comment by orlandohill** [comment]
One other thought. Could the list of source files be refactored into a variable?

**Comment by JoshuaGross** [comment]
Done - now `make` behaviour is unchanged, `make ios` will build the iOS lib. I also am now using the LIB_FILES variable.

Would it be helpful to change documentation somewhere to indicate that the `make ios` option is available? Not sure where the best place to document that is.

**Comment by orlandohill** [comment]
Looks great!

Are you able to edit the source for the manual, docs/book/book lines 624-648, to include mention of building/installing for iOS?

Is it possible to make the target names consistent with the original file? Lowercase, optionally with a dash, seems to be the GNU Make convention.
http://www.gnu.org/software/make/manual/html_node/Standard-Targets.html

Is the 'ios' target needed? It looks like invoking lib-ios would have the same effect. Not sure whether it makes sense to have the shorter alias.

**Comment by JoshuaGross** [comment]
Thanks for your thorough comments! Let me know if I've missed anything and if the documentation looks good.

**Comment by orlandohill** [comment]
Looks perfect! Thanks for taking the time to contribute!

**Pull request merged**
